export const PRODUCTS = [
  {
    id: 1,
    name_ru: 'Телевизор Volto Smart 32" (HD)',
    name_uz: 'Televizor Volto Smart 32" (HD)',
    price: '1399000',
    image: 'tvs/tv_32.jpg',
    carouselImg: 'tvs/tv_32-0.jpg; tvs/tv_43-1.jpg; tvs/tv_43-2.jpg; tvs/tv_43-3.jpg; tvs/tv_43-4.jpg; tvs/tv_43-5.jpg',
    description_ru: 'Smart TV работает на базе ОС Android 11 с ПО Family. Телевизор воспроизводит четкое изображение с насыщенными цветами, постановками, игровыми фильмами и эфирными передачами, еще более реалистичными. Встроенный цифровой тюнер DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 позволяет принимать 199 индивидуальных и 400 цифровых каналов, а также имеется встроенный цифровой 3D-фильтр, оптимизирующий изображение при наличии помех (снег на антенне или грозе).',
    description_uz: "Smart TV Family dasturi bilan Android 11 operatsion tizimida ishlaydi. Televizor rang-barang ranglarga ega tiniq suratlar ishlab chiqaradi, sahnalar, badiiy filmlar va translyatsiyalar yanada realistik. O'rnatilgan DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 raqamli tyuner 199 ta individual va 400 ta raqamli kanallarni qabul qilish imkonini beradi, shuningdek, o'rnatilgan raqamli 3D filtri ham mavjud. shovqin mavjudligida tasvir (antennadagi qor yoki momaqaldiroq).",
    characteristic_ru: "Тип телевизора: LED Диагональ 32'. Разрешение экрана: 1366*768. Разрешение картинки: HD. Тип: Smart TV. Подключение: Wi-Fi, LAN. Пульт: Magic Remote в комплекте. Голосовой поиск. Многоязыковое меню. Потребляемая мощность: 164 Вт. Страна производства: UZ. Гарантийный срок: 3 года от производителя.",
    characteristic_uz: "Televizor turi: LED diagonali 32'. Ekran o'lchamlari: 1366*768. Yuqori aniqlikdagi rasmlar: HD. Turi: Smart TV. Ulanish:  Wi-Fi, LAN. Pult: Magic Remote to'plamga kiritilgan. Ovozli qidiruv. Ko'p tilli menyu. Quvvat iste'moli: 164 Vt. Ishlab chiqarilgan mamlakat: UZ. Kafolat muddati: 3 yil ishlab chiqaruvchidan.",
  },
  {
    id: 2,
    name_ru: 'Телевизор Volto 32 Smart Webos',
    name_uz: 'Televizor Volto 32 Smart Webos',
    price: '1888000',
    image: 'tvs/tv_32.jpg',
    carouselImg: 'tvs/tv_32-0.jpg; tvs/tv_43-1.jpg; tvs/tv_43-2.jpg; tvs/tv_43-3.jpg; tvs/tv_43-4.jpg; tvs/tv_43-5.jpg',
    description_ru: 'Smart TV работает на базе ОС Android 11 с ПО Family. Телевизор воспроизводит четкое изображение с насыщенными цветами, постановками, игровыми фильмами и эфирными передачами, еще более реалистичными. Встроенный цифровой тюнер DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 позволяет принимать 199 индивидуальных и 400 цифровых каналов, а также имеется встроенный цифровой 3D-фильтр, оптимизирующий изображение при наличии помех (снег на антенне или грозе).',
    description_uz: "Smart TV Family dasturi bilan Android 11 operatsion tizimida ishlaydi. Televizor rang-barang ranglarga ega tiniq suratlar ishlab chiqaradi, sahnalar, badiiy filmlar va translyatsiyalar yanada realistik. O'rnatilgan DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 raqamli tyuner 199 ta individual va 400 ta raqamli kanallarni qabul qilish imkonini beradi, shuningdek, o'rnatilgan raqamli 3D filtri ham mavjud. shovqin mavjudligida tasvir (antennadagi qor yoki momaqaldiroq).",
    characteristic_ru: "Тип телевизора: LED Диагональ 32'. Разрешение экрана: 1920*1080. Разрешение картинки: HD. Тип: webOS Smart TV. Подключение: Wi-Fi, LAN, HDMI, USB, Bluetooth. Пульт: Magic Remote в комплекте. Голосовой поиск. Многоязыковое меню. Потребляемая мощность: 164 Вт. Страна производства: UZ. Гарантийный срок: 3 года от производителя.",
    characteristic_uz: "Televizor turi: LED diagonali 32'. Ekran o'lchamlari: 1920*1080. Yuqori aniqlikdagi rasmlar: HD. Turi: webOS Smart TV. Ulanish: Wi-Fi, LAN, HDMI, USB, Bluetooth. Pult: Magic Remote to'plamga kiritilgan. Ovozli qidiruv. Ko'p tilli menyu. Quvvat iste'moli: 164 Vt. Ishlab chiqarilgan mamlakat: UZ. Kafolat muddati: 3 yil ishlab chiqaruvchidan.",
  },
  {
    id: 3,
    name_ru: 'Телевизор Volto Smart 43" (Full HD)',
    name_uz: 'Televizor Volto Smart 43" (Full HD)',
    price: '2299000',
    image: 'tvs/tv_43.jpg',
    carouselImg: 'tvs/tv_43-0.jpg; tvs/tv_43-1.jpg; tvs/tv_43-2.jpg; tvs/tv_43-3.jpg; tvs/tv_43-4.jpg; tvs/tv_43-5.jpg',
    description_ru: 'Smart TV работает на базе ОС Android 11 с ПО Family. Телевизор воспроизводит четкое изображение с насыщенными цветами, постановками, игровыми фильмами и эфирными передачами, еще более реалистичными. Встроенный цифровой тюнер DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 позволяет принимать 199 индивидуальных и 400 цифровых каналов, а также имеется встроенный цифровой 3D-фильтр, оптимизирующий изображение при наличии помех (снег на антенне или грозе).',
    description_uz: "Smart TV Family dasturi bilan Android 11 operatsion tizimida ishlaydi. Televizor rang-barang ranglarga ega tiniq suratlar ishlab chiqaradi, sahnalar, badiiy filmlar va translyatsiyalar yanada realistik. O'rnatilgan DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 raqamli tyuner 199 ta individual va 400 ta raqamli kanallarni qabul qilish imkonini beradi, shuningdek, o'rnatilgan raqamli 3D filtri ham mavjud. shovqin mavjudligida tasvir (antennadagi qor yoki momaqaldiroq).",
    characteristic_ru: "Тип телевизора: LED Диагональ 43' (109.2). Разрешение экрана: 1980*1080. Высокое разрешение картинки: Full HD. Тип: Smart TV. Подключение: Wi-Fi, LAN. Пульт: Magic Remote в комплекте. Голосовой поиск. Многоязыковое меню. Потребляемая мощность: 164 Вт. Страна производства: UZ. Гарантийный срок: 3 года от производителя.",
    characteristic_uz: "Televizor turi: LED diagonali 43' (109.2). Ekran o'lchamlari: 1980*1080. Yuqori aniqlikdagi rasmlar: Full HD. Turi: Smart TV. Ulanish:  Wi-Fi, LAN. Pult: Magic Remote to'plamga kiritilgan. Ovozli qidiruv. Ko'p tilli menyu. Quvvat iste'moli: 164 Vt. Ishlab chiqarilgan mamlakat: UZ. Kafolat muddati: 3 yil ishlab chiqaruvchidan.",
  },
  {
    id: 4,
    name_ru: 'Телевизор Volto 43 Smart Webos',
    name_uz: 'Televizor Volto 43 Smart Webos',
    price: '2888000',
    image: 'tvs/tv_43.jpg',
    carouselImg: 'tvs/tv_43-0.jpg; tvs/tv_43-1.jpg; tvs/tv_43-2.jpg; tvs/tv_43-3.jpg; tvs/tv_43-4.jpg; tvs/tv_43-5.jpg',
    description_ru: 'Smart TV работает на базе ОС Android 11 с ПО Family. Телевизор воспроизводит четкое изображение с насыщенными цветами, постановками, игровыми фильмами и эфирными передачами, еще более реалистичными. Встроенный цифровой тюнер DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 позволяет принимать 199 индивидуальных и 400 цифровых каналов, а также имеется встроенный цифровой 3D-фильтр, оптимизирующий изображение при наличии помех (снег на антенне или грозе).',
    description_uz: "Smart TV Family dasturi bilan Android 11 operatsion tizimida ishlaydi. Televizor rang-barang ranglarga ega tiniq suratlar ishlab chiqaradi, sahnalar, badiiy filmlar va translyatsiyalar yanada realistik. O'rnatilgan DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 raqamli tyuner 199 ta individual va 400 ta raqamli kanallarni qabul qilish imkonini beradi, shuningdek, o'rnatilgan raqamli 3D filtri ham mavjud. shovqin mavjudligida tasvir (antennadagi qor yoki momaqaldiroq).",
    characteristic_ru: "Тип телевизора: LED Диагональ 43' (109.2). Разрешение экрана: 1980*1080. Высокое разрешение картинки: Full HD. Тип: webOS Smart TV. Подключение: Wi-Fi, LAN. Пульт: Magic Remote в комплекте. Голосовой поиск. Многоязыковое меню. Потребляемая мощность: 164 Вт. Страна производства: UZ. Гарантийный срок: 3 года от производителя.",
    characteristic_uz: "Televizor turi: LED diagonali 43' (109.2). Ekran o'lchamlari: 1980*1080. Yuqori aniqlikdagi rasmlar: Full HD. Turi: webOS Smart TV. Ulanish:  Wi-Fi, LAN. Pult: Magic Remote to'plamga kiritilgan. Ovozli qidiruv. Ko'p tilli menyu. Quvvat iste'moli: 164 Vt. Ishlab chiqarilgan mamlakat: UZ. Kafolat muddati: 3 yil ishlab chiqaruvchidan.",
  },
  {
    id: 5,
    name_ru: 'LED VOLTO 55 VUW-9000 Smart',
    name_uz: 'LED VOLTO 55 VUW-9000 Smart',
    price: '4500000',
    image: 'tvs/tv_55.jpg',
    carouselImg: 'tvs/tv_55-0.jpg; tvs/tv_43-1.jpg; tvs/tv_43-2.jpg; tvs/tv_43-3.jpg; tvs/tv_43-4.jpg; tvs/tv_43-5.jpg',
    description_ru: 'Smart TV работает на базе ОС Android 11 с ПО Family. Телевизор воспроизводит четкое изображение с насыщенными цветами, постановками, игровыми фильмами и эфирными передачами, еще более реалистичными. Встроенный цифровой тюнер DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 позволяет принимать 199 индивидуальных и 400 цифровых каналов, а также имеется встроенный цифровой 3D-фильтр, оптимизирующий изображение при наличии помех (снег на антенне или грозе).',
    description_uz: "Smart TV Family dasturi bilan Android 11 operatsion tizimida ishlaydi. Televizor rang-barang ranglarga ega tiniq suratlar ishlab chiqaradi, sahnalar, badiiy filmlar va translyatsiyalar yanada realistik. O'rnatilgan DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 raqamli tyuner 199 ta individual va 400 ta raqamli kanallarni qabul qilish imkonini beradi, shuningdek, o'rnatilgan raqamli 3D filtri ham mavjud. shovqin mavjudligida tasvir (antennadagi qor yoki momaqaldiroq).",
    characteristic_ru: "Тип телевизора: LED Диагональ 55' (139.7). Разрешение экрана: 3840*2160. Высокое разрешение картинки: 4K UHD. Тип: webOS Smart TV. Подключение: Wi-Fi, LAN. Пульт: Magic Remote в комплекте. Голосовой поиск. Многоязыковое меню. Потребляемая мощность: 164 Вт. Страна производства: UZ. Гарантийный срок: 3 года от производителя.",
    characteristic_uz: "Televizor turi: LED diagonali 55' (139.7). Ekran o'lchamlari: 3840*2160. Yuqori aniqlikdagi rasmlar: 4K UHD. Turi: webOS Smart TV. Ulanish:  Wi-Fi, LAN. Pult: Magic Remote to'plamga kiritilgan. Ovozli qidiruv. Ko'p tilli menyu. Quvvat iste'moli: 164 Vt. Ishlab chiqarilgan mamlakat: UZ. Kafolat muddati: 3 yil ishlab chiqaruvchidan.",
  },
  {
    id: 6,
    name_ru: 'Телевизор Volto Led 75VUW-9000 Smart',
    name_uz: 'Televizor Volto Led 75VUW-9000 Smart',
    price: '10999000',
    image: 'tvs/tv_75.jpg',
    carouselImg: 'tvs/tv_75-0.jpg; tvs/tv_43-1.jpg; tvs/tv_43-2.jpg; tvs/tv_43-3.jpg; tvs/tv_43-4.jpg; tvs/tv_43-5.jpg',
    description_ru: 'Smart TV работает на базе ОС Android 11 с ПО Family. Телевизор воспроизводит четкое изображение с насыщенными цветами, постановками, игровыми фильмами и эфирными передачами, еще более реалистичными. Встроенный цифровой тюнер DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 позволяет принимать 199 индивидуальных и 400 цифровых каналов, а также имеется встроенный цифровой 3D-фильтр, оптимизирующий изображение при наличии помех (снег на антенне или грозе).',
    description_uz: "Smart TV Family dasturi bilan Android 11 operatsion tizimida ishlaydi. Televizor rang-barang ranglarga ega tiniq suratlar ishlab chiqaradi, sahnalar, badiiy filmlar va translyatsiyalar yanada realistik. O'rnatilgan DVB-T/DVB-T2/DVB-C/DVB-S/DVB-S2 raqamli tyuner 199 ta individual va 400 ta raqamli kanallarni qabul qilish imkonini beradi, shuningdek, o'rnatilgan raqamli 3D filtri ham mavjud. shovqin mavjudligida tasvir (antennadagi qor yoki momaqaldiroq).",
    characteristic_ru: "Тип телевизора: LED Диагональ 75' (190.5). Разрешение экрана: 3840*2160. Высокое разрешение картинки: 4K Ultra HD. Тип: webOS Smart TV. Подключение: Wi-Fi, LAN. Пульт: Magic Remote в комплекте. Голосовой поиск. Многоязыковое меню. Потребляемая мощность: 164 Вт. Страна производства: UZ. Гарантийный срок: 3 года от производителя.",
    characteristic_uz: "Televizor turi: LED diagonali 75' (190.5). Ekran o'lchamlari: 3840*2160. Yuqori aniqlikdagi rasmlar: 4K Ultra HD. Turi: webOS Smart TV. Ulanish:  Wi-Fi, LAN. Pult: Magic Remote to'plamga kiritilgan. Ovozli qidiruv. Ko'p tilli menyu. Quvvat iste'moli: 164 Vt. Ishlab chiqarilgan mamlakat: UZ. Kafolat muddati: 3 yil ishlab chiqaruvchidan.",
  },
]
